version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container-bebetter
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --max_allowed_packet=64M --wait_timeout=28800 --interactive_timeout=28800

volumes:
  mysql-data:
